name: task_manager_app
description: "Example Task Manager App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hydrated_bloc: ^9.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.5
#  go_router: ^14.1.3
  replay_bloc: ^0.2.7
  google_fonts: ^6.2.1
  reactive_forms: ^17.0.1
  firebase_core: ^2.31.1
  firebase_crashlytics: ^3.5.6
  firebase_analytics: ^10.10.6
  equatable: ^2.0.5
  http_interceptor: ^2.0.0-beta.8
  fetch_client: ^1.1.1
  cronet_http: ^1.3.0
  cupertino_http: ^1.5.0
  flutter_hooks: ^0.20.5
  reactive_flutter_typeahead: ^2.1.1
  firebase_auth: ^4.16.0
  google_sign_in: ^6.3.0
  sign_in_button: ^3.2.0
  uuid: ^4.5.1
  mobile_device_identifier: ^0.0.3
  package_info_plus: ^8.3.0
  envied: ^1.1.1

dependency_overrides:
  go_router: 7.1.1
  flutter_keyboard_visibility: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.10
  very_good_analysis: ^5.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - images/
